// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using CountriesServer.DbContextClasses;

#nullable disable

namespace CountriesServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240518223204_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.19");

            modelBuilder.Entity("CountriesServer.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Agriculture")
                        .HasColumnType("REAL");

                    b.Property<double>("Area")
                        .HasColumnType("REAL");

                    b.Property<double>("Birthrate")
                        .HasColumnType("REAL");

                    b.Property<double>("Climate")
                        .HasColumnType("REAL");

                    b.Property<double>("CoastlineRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("Deathrate")
                        .HasColumnType("REAL");

                    b.Property<int>("GDP")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Industry")
                        .HasColumnType("REAL");

                    b.Property<double>("InfantMortality")
                        .HasColumnType("REAL");

                    b.Property<double>("Literacy")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NetMigration")
                        .HasColumnType("REAL");

                    b.Property<double>("Phones")
                        .HasColumnType("REAL");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PopulationDensity")
                        .HasColumnType("REAL");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
